# Generated by Django 5.2.3 on 2025-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_image_encode',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
